services:
  - type: web
    name: pivot-devs-demo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
